version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT
      - SoapEndpoint
      - SqlConnectionString
      - SqlQuery
      - PgConnectionString

  sqlserver:
    image: "microsoft/mssql-server-linux"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=BaldEagle123
    volumes:
      - ./sql-seed:/sql-seed

  postgres:
    image: "postgres"
    volumes:
      - ./sql-seed:/sql-seed